import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.read.biff.BiffException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author VESTATEST
 */
public class GUI extends javax.swing.JFrame {
	private boolean path = false, excel = false;

	Applications a = new Applications();

	/**
	 * Creates new form NewJFrame
	 */
	public GUI() {
		initComponents();
		this.setResizable(false);
		this.setLocation(300, 200);
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		txtExcel = new javax.swing.JTextField();
		bExcel = new javax.swing.JButton();
		txtPath = new javax.swing.JTextField();
		bPath = new javax.swing.JButton();
		bFire = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		bar = new javax.swing.JLabel();
		statustext = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		bExcel.setText("Browse");
		bExcel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bExcelActionPerformed(evt);
			}
		});

		bPath.setText("Browse");
		bPath.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bPathActionPerformed(evt);
			}
		});

		bFire.setText("Export");
		bFire.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bFireActionPerformed(evt);
			}
		});

		jLabel1.setText("Select an Excel File");

		jLabel2.setText("Select Matelo Project Path :");

		jLabel3.setText("Status :");

		jLabel6.setText("0%");

		jLabel7.setText("100%");

		statustext.setText("Waiting for files");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(jLabel6)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabel7))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										txtExcel,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										320,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(bExcel))
																				.addComponent(jLabel1)
																				.addComponent(jLabel2)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										txtPath,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										320,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(bPath))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(bFire)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(jLabel3)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(statustext)))
																.addGap(0, 0, Short.MAX_VALUE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtExcel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(bExcel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(bPath))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(bar)
												.addComponent(jLabel6).addComponent(jLabel7))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(bFire).addComponent(jLabel3).addComponent(statustext))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void bExcelActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			// TODO add your handling code here:
			txtExcel.setText(a.getF().selectXlFile());
		} catch (BiffException ex) {
			Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void bPathActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		txtPath.setText(a.getF().directoryPath());

	}

	private void bFireActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		if (!txtExcel.getText().isEmpty()) {
			excel = true;
		}
		if (!txtPath.getText().isEmpty()) {
			path = true;
		}
		if (path && excel) {
			statustext.setText("Ready");
			this.repaint();
			a.getAllStates();
			statustext.setText("Process");
			this.repaint();
			a.setStateDetails();
			a.generatePathList();
			a.separateStates();
			a.addTerminateState();
			a.getAllTransitions();
			a.tAnalyze(a.getTransitionList());
			a.mergeTransDiag();
			a.generateIds();
			a.assignDominatorTrees();
			a.processTransitions();
			a.generateOrgIds();
			a.calculateOutgoings();
			a.recalculateStatePositions();
			a.calculateOutgoingValues();
			a.assignValues();
			a.getF().findProfileLib();
			a.createDiagramFiles(a.getF().getProjectPath());
			a.sortDiagrams();
			a.checkMacroStates();
			a.output();
			a.processPRT();
			a.processIchains();
			statustext.setText("Complate");
			JOptionPane.showMessageDialog(null, "Done", "Success", JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
			this.repaint();
		} else if (!excel) {
			JOptionPane.showMessageDialog(null, "Select Excel File", "ERROR", JOptionPane.WARNING_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "Select Project Path", "ERROR", JOptionPane.WARNING_MESSAGE);

		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton bExcel;
	private javax.swing.JButton bFire;
	private javax.swing.JButton bPath;
	private javax.swing.JLabel bar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel statustext;
	private javax.swing.JTextField txtExcel;
	private javax.swing.JTextField txtPath;
	// End of variables declaration
}
